
```{r}
summary(taset)
```
```{r}
summary(ur.df(bir))
```
```{r}
summary(ur.df(cpi))
```
```{r}
summary(ur.df(fdr))
```
```{r}
summary(ur.df(log_aset))
```
```{r}
summary(ur.df(log_aset5))
```
```{r}
summary(ur.df(log_aset10))
```
```{r}
summary(ur.df(log_aset15))
```
```{r}
summary(ur.df(diff(bir)))
```
```{r}
summary(ur.df(diff(cpi)))
```
```{r}
summary(ur.df(diff(fdr)))
```
```{r}
summary(ur.df(diff(log_aset)))
```
```{r}
summary(ur.df(diff(log_aset5)))
```
```{r}
summary(ur.df(diff(log_aset10)))
```
```{r}
summary(ur.df(diff(log_aset15)))
```
```{r}
VARselect(varaset, lag.max = 8)
```

```{r}
tv <- TVAR(varaset, lag=1, nthresh=1, thDelay=1, trim=0.1, mTh=1, plot=FALSE)
```
```{r}
summary(tv)
```
```{r}
print(tv)
```

```{r}
plot(tv)
```
```{r}
VARselect(simaset, lag.max = 6)
```

```{r}
tvsim <- TVAR(simaset, lag=1, nthresh=1, thDelay=1, trim=0.1, mTh=1, plot=FALSE)
```
```{r}
plot(tvsim)
```
```{r}
summary(tvsim)
```
```{r}
print(tvsim)
```
```{r}
nonlinearityTest(bir, verbose = T)
```
```{r}
summary(varaset)
```
```{r}
summary(simaset)
```

